import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignInButton, SignOutButton, useUser, UserProfile, UserButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {user.isSignedIn ? 
          /* Display user profile and Sign Out Button */
          <> <UserButton appearance={{
            elements: {
              className: "absolute top-0 right-0 h-16 w-16"
            }
          }}/>
           <div className="bg-red-500 text-white py-2 px-4 rounded cursor-pointer"><SignOutButton /></div> </>
          :
          /* Display Sign in Button */
          <div className="bg-red-500 text-white py-2 px-4 rounded cursor-pointer"><SignInButton /></div>}
        </div>
      </main>
    </>
  );
};

export default Home;
